- samples/USCoreMedicationRequest.fsh
- samples/USCorePatient.fsh
- samples/USCorePatientExample.fsh
- samples/USCorePediatricBMIForAge.fsh
- samples/USCorePractitioner.fsh
- samples/USCorePulseOximetry.fsh
This adds nice syntactical shortcuts to the samples:
* One line MS
* Dropping `extension`, so `extension[us-core-race].extension[ombCategory][0].valueCoding` -> `us-core-race.ombCategory[0].valueCoding`
> Syntax shortcuts (MS and extension)

- input-cache/schemas-r5/fhir-single.xsd
- input/pagecontent/index.md
- input/shorthand-ig.xml
- package-list.json
This has two fixes:
- fix the manual slicing example to use the right paths
- fix the shorthand-ig.xml and package-list.json so IG properly shows v0.1.0 (not vnull)
> Fix IG version and slice example

- input/pagecontent/reference.md
Like in the previous PR, this one was done in commits if you prefer to back out any wholesale changes related to specific features.  Or feel free to tack on a commit with your tweaks as before.
Additional thoughts as I reviewed this:
1. I left in the 🚧 icons for now, since we will merge this before all features are done in SUSHI -- but I assume that the final publication will have all 🚧 removed.
2. The IG Publisher's rendering of the angled "smart quotes" drives me crazy!
3. The heading levels don't seem right.  Should we really be starting at heading level `####`? It doesn't leave much room to go anywhere!
4. I think we should consider making all full-line code expressions use triple-tick code blocks.  The mix of single-tick and triple-tick code formatting looks sloppy to me.
5. I'm not …
> Updates to Language Reference

- input/pagecontent/reference.md
- input/pagecontent/sushi.md
- input/pagecontent/tutorial.md
Minor edits to SUSHI, Tutorial, and Reference.
A few things to note:
* I removed the bits about bash vs. zsh because we don't use any commands that are different in zsh.  I tested the whole thing in zsh to confirm.
* The veterinarian profile is a little funny in that it says to use the `http://hl7.org/fhir/sid/ca-hc-npn` code system for qualifications, but:
* IG Publisher reports errors about it.
* According to the [Code Systems](http://hl7.org/fhir/R4/terminologies-systems.html) listing, that URL is for a different system: <img width="680" alt="image" src="https://user-images.githubusercontent.com/2278253/76484729-fdd33680-63f0-11ea-9510-e3a0ecf305cf.png">
* But according to [this page](https://build.fhir.org/ig/HL7/UTG/CodeSystem-v3-HealthcareProviderTaxonomyHIPAA.html), it's for …
> Edits to SUSHI, Tutorial, and Reference

- input/pagecontent/reference.md
Fixes a suspected typo that I noticed while reading the docs.  Observed in the [Defining Items section of the Language Reference](https://build.fhir.org/ig/HL7/fhir-shorthand/reference.html#defining-items).
Changes `Pmarkdown` to `markdown`.
> Suspected Typo

- input/pagecontent/reference.md
This section of the documentation was incorrectly missing the `and` and would not run correctly if people tried to copy and paste it. As someone did here https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Error.20in.20SUSHI.20with.20extensions.3F. This fixes that typo.
> Fixing a typo in the description of inline extensions

- input/pagecontent/reference.md
Add information about parameterized rule sets. This results in changes to the following sections:
- 3.5.7 "Insert Rules" now contains two subsections: one for inserting a rule set without parameters, and one for inserting a rule set with parameters.
- 3.6.8 "Defining Rule Sets" now contains two subsections: one for defining a rule set without parameters, and one for defining a rule set with parameters.
- 3.8 "Appendix: Formal Grammar" now contains two subsections, as the formal grammar has been split into separate files for the parser and the lexer.
> Add information about defining and inserting parameterized rule sets

- input/pagecontent/overview.md
- input/pagecontent/reference.md
A few things got mixed up in the concurrent editing and merges in the logical and resources PR.  This PR fixes them.
This PR also moves the _AddElement rules_ section in the Overview back to its original location because all of the rule types are listed in alphabetical order.
> Tweaks to logical docs

- input/pagecontent/reference.md
This adds documentation for the functionality to put a path before an insert rule, for example, something like: 
```
RuleSet: NameRules
* family MS
* given MS
Profile: MyPatientProfile
Parent: Patient
* name insert NameRules
* deceased[x] only deceasedBoolean
// More profile rules
```
> Document insert rules with paths

- input/pagecontent/reference.md
Indicate that type rules (e.g. "only") can also be used to constrain canonical types and include a few simple examples.
> Constrain Canonicals

- input/includes/menu.xml
- input/pagecontent/reference.md
This looks so good, @markkramerus.  Really, really nice job.  I like what you've done!
I've applied most of my suggestions as changes (some of which I'll comment on if I feel they need explanation).  In addition to the changes I've made, I have the following overall comments:
* I feel like the note about pages that are informative (Home and Overview) is highlighted too much.  It is distracting.  I'd suggest toning it down.
* The section on version numbering seems a little out of place, as the previous sections (Projects, Files, FHIR Version, External IGs) are more about how projects can be organized/defined, whereas Version Numbering is about the FSH Spec itself (i.e., it is more _meta_ than the others).  I almost feel like that belongs more in the Home or Overview than in the actual …
> Minor tweaks and fixes to reorganization

- input/pagecontent/reference.md
This updates the grammar so that it is accurate with respect to what is currently on the master branch of SUSHI. The updates were needed to fix this bug: https://github.com/FHIR/sushi/issues/872, and were made in this PR: https://github.com/FHIR/sushi/pull/880.
@markkramerus, we weren't sure how you would want to handle this. There is not yet a new version of SUSHI released that uses this grammar, but it is on the master branch and will go out in the next release.
> Update grammar so that alias accepts SEQUENCE and CODE

- _genonce.bat
- _updatePublisher.bat
- input/ImplementationGuide-hl7.fhir.uv.shorthand.xml
- input/includes/menu.xml
- input/pagecontent/change_log.md
This adds a list-based change log detailing the substantive changes in the spec from STU1 to Sep 2021 ballot to the Mixed Normative / TU release.
~~I considered representing the list as a table w/ rows for "Change", "Level", "Specification Links" -- but ran out of time before I had to step out.  I can try the table if you think it might be preferred.~~
Compare this with the table-based changelog PR (#131) and choose your favorite.
See it here: http://build.fhir.org/ig/HL7/fhir-shorthand/branches/changelog/change_log.html
> List-Based Change Log

- input/pagecontent/reference.md
In some places of the `Mapping` description, the `Id` keyword is missing. It was already present in the examples and in the `Mapping` keyword descriptions, but missing from the global keyword table and the textual description of `Mapping` keywords.
The keyword is supported by SUSHI and not required, so I've added it as suggested (since `StructureDefinition.mapping.identity` is needed anyway).
The quick reference sheet is also wrong and would need an update.
> Add missing `Id` keyword for Mappings

- input/pagecontent/reference.md
Add an example using an exponent to the syntax substitution table.
See also the [SUSHI PR](https://github.com/FHIR/sushi/pull/1203) that updates the FSH grammar.
> Add exponent notation to NUMBER token

- input/pagecontent/change_log.md
This adds a new entry to the change log for the 3.0.0 ballot. A summary of the changes (to the change log lol):
- I promoted everything that was previously listed as Trial Use to Normative, except for the item for support for integer64 and CodeableReference
- I added a placeholder for the new pieces we're planning to document but aren't in the IG yet (like the RuleSet `[[ ]]` syntax)
- I looked through the commits since the last change log commit and added a few bullet points to note other things that had changed but didn't feel that they belonged in the separate Normative/Trial Use features lists.
One piece I'm not sure about is I referenced this entry as `FHIR Shorthand 3.0.0 Mixed Normative / Trial Use Ballot 1`, which I'm not actually sure about, but that was my best guess since there …
> Update Change Log

- input/pagecontent/reference.md
This PR adds some language and an example to clarify how to use hard and soft indices to reference items in a slice.
> Clarify use of indices with slice paths

- input/pagecontent/change_log.md
- input/pagecontent/reference.md
This PR adds documentation for the updates to Path Rules that will be introduced in SUSHI as part of [SUSHI #1252](https://github.com/FHIR/sushi/pull/1252).
It also updates Table 7 to correctly show that Mappings can have Path Rules. This is documented elsewhere in the Spec, so this is just a correction.
*Note for reviewers*: Path Rules are marked as TU in the current version of the FSH Spec (2.0). In preparation for the 3.0 version of FSH, the TU marking was removed. However, this is brand new functionality for Path Rules. Since it only applies to Instances in specific cases, I marked the _new_ uses of Path Rules as TU here. However, there can probably be an argument made to keep all of Path Rules marked as TU. Please let me know what approach you think is best and I can update …
> Updated Path Rule rules

- input/pagecontent/change_log.md
- input/pagecontent/reference.md
Adds documentation pertaining to [SUSHI PR 1282](https://github.com/FHIR/sushi/pull/1282)
Add link to Extension definitions to change log.
Add Context keyword to keyword summary tables.
Add examples using Context keyword, marked as trial use.
> Add Context keyword for Extension

- _genonce.sh
- input/includes/tu-span.html
- input/pagecontent/change_log.md
- input/pagecontent/reference.md
This updates the spec documentation to indicate that Invariant definitions now support rules. As a result of this, the `Description` and `Severity` keywords are no longer REQUIRED since you can set those values via rules. I've marked relevant sections using the TU marker and background color.
When reviewing, note changes in the following locations:
* [Table 6. Relationships between declarations and keywords in FSH](https://build.fhir.org/ig/HL7/fhir-shorthand/branches/invariant-rules/reference.html#t6)
* [Table 7. Relationships betwen FSH items and FSH rules](https://build.fhir.org/ig/HL7/fhir-shorthand/branches/invariant-rules/reference.html#t6)
* [Section 3.5.6. Defining Invariants](https://build.fhir.org/ig/HL7/fhir-shorthand/branches/invariant-rules/reference.html#defining-invariants) …
> Document Invariant Rules

- input/includes/menu.xml
- input/pagecontent/reference.md
This updates the link in the menu to the antlr folder to link to the official 3.0.0 version. I also included the new grammar and lexer files in the short grammar section on the reference page, as well as updating the existing links there. If it is confusing including two grammar files and two lexer files, I can replace them with one link to the antlr folder, which will mirror the menu item.
> Use released SUSHI 3.0.0 when linking to FSH Grammar files

- input/pagecontent/change_log.md
- input/pagecontent/reference.md
Adds new reserved keywords that have been added in other PRs: `Characteristics`, `Context` (both marked as TU)
Adds missing reserved words: `contentReference`
Add sentence about other types of reserved words: `Reference`, `CodeableReference` (marked as TU), `Canonical`
> Update the Reserved Words section

- input/pagecontent/change_log.md
- input/pagecontent/reference.md
Adds documentation for using `CodeableReference(...)` in Add Element and Type rules.
One question I have is - in the FSH Language Basics section, there is a section specifically for References and Canonicals, which have a special syntax similar to CodeableReference. Does it make sense to add a whole section for CodeableReference here as well? Right now, this branch just describes where/how you can use the keyword itself.
Also, as of now, `CodeableReference` is not used directly in Assignment Rules, so there is no documentation for that. But if we decide to add that, I'll update this PR.
> Add documentation for CodeableReference keyword uses

- input/pagecontent/change_log.md
- input/pagecontent/reference.md
The Characteristics keyword is used with logical models. It should be used to specify the type characteristics of the model.
This documentation is applicable to [SUSHI PR 1293](https://github.com/FHIR/sushi/pull/1293), which adds the Characteristics keyword to the grammar.
> Add Characteristics keyword

- input/pagecontent/change_log.md
- input/pagecontent/reference.md
This PR adds specification for using caret rules to set metadata on concepts that are included or excluded in value set definitions. We expect this will be primarily used to access `ValueSet.compose.include.concept.designation`. We've discussed this some but never laid out the exact rules -- so please feel free to speak up if you disagree w/ the approach.
I also changed a series of Note 1 - Note 5 to a simple bulleted list, as the series of notes looked strange -- and CodeSystem specifies its notes as a simple bulleted list (so there is precedent).
You can view the rendered version of my changes from the [CI build of this branch](https://build.fhir.org/ig/HL7/fhir-shorthand/branches/valueset-carets/reference.html#defining-value-sets).
> Support caret path assignments for concepts in Value Sets

- publication-request.json
This PR adds the required `publication-request.json` file as documented [here](https://confluence.hl7.org/display/FHIR/IG+Publication+Request+Documentation).
> publication-request.json

- FHIR-shorthand.xml
- publication-request.json
FMG has approved FSH R3 for ballot with the following contingencies:
* The path in the publication-request.json file should be http (not https).
* The JIRA spec file needs to be updated.
This PR resolves both issues. Note that the Jira Spec file also needs to be updated in the JIRA-Spec-Artifacts repo, so there is a corresponding PR for that here: https://github.com/HL7/JIRA-Spec-Artifacts/pull/778.
> Pre-ballot Fixes

- input/pagecontent/overview.md
This PR contains a batch of changes that were agreed upon as part of the FSH ballot resolution process. These changes are in the overview page. The following Jira issues were addressed:
[FHIR-42159](https://jira.hl7.org/browse/FHIR-42159): Typo refers to wrong line in example
[FHIR-42346](https://jira.hl7.org/browse/FHIR-42346): Correct spelling of octothorpe
[FHIR-42299](https://jira.hl7.org/browse/FHIR-42299): Clarify target of pronoun
[FHIR-42360](https://jira.hl7.org/browse/FHIR-42360): Data types identical to the one in FHIR R5
[FHIR-42361](https://jira.hl7.org/browse/FHIR-42361): What is SD?
_Note: the Jira issue and resolution specifically reference one place "SD" is used. However, I updated a second place in the Overview page that "SD" was used._ …
> FSH 3.0 Resolutions - Overview

- input/pagecontent/overview.md
- input/pagecontent/reference.md
This PR addresses [FHIR-42345](https://jira.hl7.org/browse/FHIR-42345) by applying more consistent styling across the specification. After discussion with the team, including review of the FHIR and US Core specifications, we determined that the following things should use `code` styling:
* element paths, such as `Patient.name.given` and `name.given`
* resource attributes, such as `value[x]`
* symbols (when standing alone), such as `$` and `#`
* listed binding strengths, such as `required`, `extensible`, `preferred`, and `example`
* flags, such as `MU`
* slice names, such as `bpSystolic` and `bpDiastolic`
* Author-defined FSH entity names, such as `LateralityExtension`
* Aliases, such as `$LOINC`,
* FSH codes, such as `$LOINC#1234-5` and `#active`
Please review to ensure I've applied these …
> Fsh 3.0 Resolutions: Styling
